theme: minima
title: My Projects
author: Muhammad Stracey
email: strmuh001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 I am a huge Machine Learning (ML) and Artificial Intelligence (AI) nerd! 
 With a background in Mechanical Engineering and more specifically Metallurgy, I have a keen interest
 in how ML and AI can be used to better understand these fields. With it's complex behaviour and high interconnectivity,
 material microstructure is an ideal candidate for the application of ML and AI techniques. Using Python with various third-party packages,
 I have worked on various projects exploring microstructure analysis and predictive modelling.
# social links

show_excerpts: true # set to false to remove excerpts on the homepage
